### ISSUE TITLE
Auto-adjust part size to avoid MaxUploadParts limit error

### ISSUE THREAD

**Issue by abmott** [concourse/s3-resource#87]
When using the S3 Resource in a concourse pipeline I am seeing an error on file uploads to AWS over 48 Gig.
48.83 GB / 58.06 GB [==========================>-----] 84.10 % 21.14 MB/s 39m25serror running command: MultipartUpload: upload multipart failed
	
caused by: TotalPartsExceeded: exceeded total allowed configured MaxUploadParts (10000). Adjust PartSize to fit in this limit

**Comment by jama-pivotal** [comment]
@abmott Interesting. I think the best solution here might be to check the blob size and adjust the  MaxUploadParts if you hit the limit. Normally i'd suggest exposing a parameter but that's a [Concourse Anti-Pattern: Knobs and Dials](https://github.com/concourse/concourse/wiki/Anti-Patterns) ™

**Comment by jtarchie** [comment]
This looks like an issue related to the Uploader of the Golang library [1].

Parts are determined by the PartSize, which defaults to 5MB. At 58GB at is over 11k parts, which exceeds the MaxUploadParts. It is interesting it doesn't try to auto-adjust on its own.

The library Uploader [2] would have to be modified to support some more precise configurations.

[1] https://github.com/aws/aws-sdk-go/blob/master/service/s3/s3manager/upload.go#L218-L252
[2] https://github.com/concourse/s3-resource/blob/588d61c817469a731961ecf00064809748b1115a/s3client.go#L169

**Comment by ruurdk** [comment]
@jama-pivotal are you really saying that because of this anti-pattern constraint everyone who requires to upload a file of >50GB (10000 parts * 5MB) should fork and maintain their own version of the S3 resource?

We are also hitting this issue now with the pcf backup pipelines for opsmanager which leverage BBR. This routinely produces very large files. It would be quite a burden to have to maintain a seperate S3 resource to use these pipelines.

**Comment by vito** [comment]
@ruurdk No, @jama-pivotal was making a implementation suggestion to avoid having this be fixed by a config knob, and rather have the code handle it by e.g. auto-adjusting the part size. No one's saying people should fork and maintain their own version. But hopefully someone eventually forks and PRs this fix in; we can't do everything ourselves. 😉

**Comment by ruurdk** [comment]
My bad, read it the wrong way. I submitted a PR with the proposed fix.

**Comment by jama-pivotal** [comment]
oops, sorry for not being clear @ruurdk

**Comment by jvshahid** [comment]
We just ran into the same issue.  We are running Concourse 5.5.7, which shipped with a `1.0.3` version of the resource.  AFAIU version `1.0.3` should have the fix merged above.  I am confused as to why we are still getting that error.  It is worth noting that the file size is `62351360000`, which is suspiciously an exact multiple of 10,000.

```
58.07 GB / 58.07 GB [===============================] 100.00 % 115.96 MB/s 8m32serror running command: MultipartUpload: upload multipart failed
	upload id: YnpeIndFM1LDw6VgRkrjkYPN3FIrCtOlkKY35zgyCMLQ_UKJaQMGpMPCw9dm0enN6bsUUcvZWS_EpVIQ2_ldfHDmD936DPAxUVW4sz70c4iHlK3UYJXBnlEMKMr6GRZgZt.l9.Lp7R3dSQkGlxze5P_H3a.rp2sgO_5.3oC0jCs-
caused by: TotalPartsExceeded: exceeded total allowed configured MaxUploadParts (10000). Adjust PartSize to fit in this limit
```

**Comment by jvshahid** [comment]
I am also wondering if there is an off by one error somewhere, but I failed to convince myself that this is even possible. The only reason I bring it up is because of [this line](https://github.com/pivotal-cf/iam-s3-resource/blob/34113184353db59ce354ae9148fa2b17101843b6/s3client.go#L199) which sets `PartSize` to the size of the file plus one.

**Comment by jvshahid** [comment]
I also forgot to mention that this job previously passed and uploaded a file whose size is `62351196160`, which is evidence that the above patch mostly works and adjusts the partition size.

**Comment by jvshahid** [comment]
FYI, I created https://github.com/concourse/s3-resource/pull/147 to address the issue we were running into that was reported in https://github.com/concourse/s3-resource/issues/87#issuecomment-578865826
